included:
  - Sources
disabled_rules:
  - force_cast
  - operator_whitespace
line_length:
  warning: 180
type_body_length:
  warning: 320
file_length:
  warning: 560
variable_name:
  excluded:
    - e
    - id
