#!/usr/bin/perl -w

use strict;

my ($WORKSPACE, $SCHEME, $ACTION) = @ARGV;

my $buildSettings = qx{xcodebuild -workspace "WORKSPACE" -scheme "$SCHEME"};

my @args = ("-workspace", $WORKSPACE, "-scheme", $SCHEME, split(/\s+/, $ACTION));

if ($SCHEME =~ /iOS/) {
    unshift @args, "-destination", "platform=iOS Simulator,name=iPhone 7,OS=10.1";
}

if ($SCHEME =~ /OSX/) {
    unshift @args, "-destination", "platform=macOS,arch=x86_64";
}

print "xcodebuild @args\n";
exec("xcodebuild", @args);
